processed 11 tasks

init:
C: object(0,0)

task 1, line 9:
//# create-checkpoint
Checkpoint created: 1

task 2, line 11:
//# advance-epoch
Epoch advanced: 0

task 3, lines 13-15:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 1960800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, lines 17-19:
//# run 0x3::iota_system::request_add_stake --args object(0x5) object(3,0) @validator_0 --sender C
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [88, 3, 100, 30, 5, 114, 164, 43, 143, 251, 187, 202, 169, 19, 100, 96, 215, 208, 151, 225, 50, 23, 133, 187, 2, 70, 241, 232, 235, 29, 214, 199, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 14630000,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 5, line 20:
//# create-checkpoint
Checkpoint created: 3

task 6, lines 22-24:
//# advance-epoch
Epoch advanced: 1

task 7, lines 25-29:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
// TODO: Short term hack to get around indexer epoch issue
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 1960800,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 30:
//# create-checkpoint
Checkpoint created: 5

task 9, lines 32-33:
//# advance-epoch
Epoch advanced: 2

task 10, lines 34-62:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "totalStake": "3034010000000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        },
        "validatorCandidatesSize": 0,
        "inactivePoolsId": "0x23f1db8e93256dc744eb6b84142c04c2cd4fd486a6133a67a8932aed2115a408"
      },
      "totalGasFees": "1000000",
      "totalStakeRewards": "767000000000000",
      "fundSize": "14630000",
      "fundInflow": "1960800",
      "fundOutflow": "980400",
      "netInflow": "980400",
      "transactionBlocks": {
        "nodes": [
          {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            },
            "digest": "B637Xcqji8L9JzJ7Fr5mQLofUBwmZRVXShwkXX23x5t6"
          },
          {
            "kind": {
              "__typename": "EndOfEpochTransaction"
            },
            "digest": "FdnPEGUzRm4MeHdXm9a5VQyzS1jSTEsAPsg3XMH7jb5N"
          }
        ]
      }
    }
  }
}
