processed 7 tasks

task 1, lines 9-34:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5251600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 35-37:
//# run Test::M1::create_n_ids --args 1 --gas-budget 100000000000000
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 38-40:
//# run Test::M1::create_n_ids --args 256 --gas-budget 100000000000000
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, lines 41-43:
//# run Test::M1::create_n_ids --args 2048 --gas-budget 100000000000000
mutated: object(0,0)
gas summary: computation_cost: 19000000, computation_cost_burned: 19000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, lines 44-46:
//# run Test::M1::create_n_ids --args 2049 --gas-budget 100000000000000
Error: Transaction Effects Status: Move Primitive Runtime Error. Location: iota::tx_context::derive_id (function index 6) at offset 0. Arithmetic error, stack overflow, max value depth, etc.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: iota, name: Identifier("tx_context") }, function: 6, instruction: 0, function_name: Some("derive_id") }))), source: Some(VMError { major_status: MEMORY_LIMIT_EXCEEDED, sub_status: Some(2), message: Some("Creating more than 2048 IDs is not allowed"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("tx_context") }), indices: [], offsets: [(FunctionDefinitionIndex(6), 0)] }), command: Some(0) } }

task 6, line 47:
//# run Test::M1::create_n_ids --args 4096 --gas-budget 100000000000000
Error: Transaction Effects Status: Move Primitive Runtime Error. Location: iota::tx_context::derive_id (function index 6) at offset 0. Arithmetic error, stack overflow, max value depth, etc.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: iota, name: Identifier("tx_context") }, function: 6, instruction: 0, function_name: Some("derive_id") }))), source: Some(VMError { major_status: MEMORY_LIMIT_EXCEEDED, sub_status: Some(2), message: Some("Creating more than 2048 IDs is not allowed"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("tx_context") }), indices: [], offsets: [(FunctionDefinitionIndex(6), 0)] }), command: Some(0) } }
