processed 20 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-23:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-29:
//# programmable --sender A --inputs 100000 @A
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
// let's get ourselves a coin worth 1000
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 1960800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# run iota::pay::split_and_transfer --type-args iota::iota::IOTA --args object(2,0) 1000 @A --sender A
created: object(3,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2941200,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 4, lines 32-34:
//# view-object 3,0
Owner: Account Address ( A )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 1000u64,
    },
}

task 5, lines 35-37:
//# programmable --sender A --inputs object(3,0) 100 @B
//> 0: SplitCoins(Input(0), [Input(1)]);
//> TransferObjects([NestedResult(0,0)], Input(2));
created: object(5,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2941200,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 6, line 39:
//# view-object 3,0
Owner: Account Address ( A )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 900u64,
    },
}

task 7, lines 41-44:
//# view-object 5,0
Owner: Account Address ( B )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 8, lines 45-47:
//# programmable --sender A --inputs object(3,0) 100 @B
//> 0: SplitCoins(Input(0), [Input(1), Input(1)]);
//> TransferObjects([NestedResult(0,0), NestedResult(0,1)], Input(2));
created: object(8,0), object(8,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3921600,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 9, line 49:
//# view-object 3,0
Owner: Account Address ( A )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 700u64,
    },
}

task 10, line 51:
//# view-object 8,0
Owner: Account Address ( B )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(8,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 11, lines 53-55:
//# view-object 8,1
Owner: Account Address ( B )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(8,1),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 12, lines 56-59:
//# programmable --sender A --inputs object(3,0) 100 @B
//> 0: test::m1::ret_one_amount();
//> 1: SplitCoins(Input(0), [Result(0), Input(1)]);
//> TransferObjects([NestedResult(1,0), NestedResult(1,1)], Input(2));
created: object(12,0), object(12,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3921600,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 13, line 61:
//# view-object 3,0
Owner: Account Address ( A )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 500u64,
    },
}

task 14, line 63:
//# view-object 12,0
Owner: Account Address ( B )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(12,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 15, lines 65-68:
//# view-object 12,1
Owner: Account Address ( B )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(12,1),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 16, lines 69-73:
//# programmable --sender A --inputs object(3,0) 100 @B
//> 0: test::m1::ret_one_amount();
//> 1: SplitCoins(Input(0), [Result(0), Input(1)]);
//> 2: MakeMoveVec<iota::coin::Coin<iota::iota::IOTA>>([NestedResult(1,0), NestedResult(1,1)]);
//> test::m1::transfer_(Result(2), Input(2));
created: object(16,0), object(16,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3921600,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 17, line 75:
//# view-object 3,0
Owner: Account Address ( A )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 300u64,
    },
}

task 18, line 77:
//# view-object 16,0
Owner: Account Address ( B )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(16,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}

task 19, line 79:
//# view-object 16,1
Owner: Account Address ( B )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(16,1),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 100u64,
    },
}
