processed 8 tasks

task 1, lines 9-103:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "3fUrRjNoRtQ1QqGCH8r4WL31rTu7vQnArVmf1c8ccB4r",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXEzMl8zMiIsImMiOjB9",
                            "node": {
                              "name": "uq32_32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXE2NF82NCIsImMiOjB9",
                            "node": {
                              "name": "uq64_64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbl9tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "coin_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW0iLCJjIjowfQ",
                            "node": {
                              "name": "iota_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW1fc3RhdGVfaW5uZXIiLCJjIjowfQ",
                            "node": {
                              "name": "iota_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tlZF9zdGFraW5nIiwiYyI6MH0",
                            "node": {
                              "name": "timelocked_staking"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::iota_system::IotaSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x4e3bdeec416e73f8f25fb9d13fa58c077707c2dcccaed8f7d7c2ca9c494142e2",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0xe667d75db0adb1c1c93efa5b4ec1867293b98def10dfed4b919182637334c0ab",
                            "size": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzc191bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "address_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXMiLCJjIjowfQ",
                            "node": {
                              "name": "alias"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "alias_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFzaWNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "basic_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXhwaXJhdGlvbl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "expiration_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaXJjMjciLCJjIjowfQ",
                            "node": {
                              "name": "irc27"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0IiwiYyI6MH0",
                            "node": {
                              "name": "nft"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0X291dHB1dCIsImMiOjB9",
                            "node": {
                              "name": "nft_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhcmR1c3RfdXBncmFkZV9sYWJlbCIsImMiOjB9",
                            "node": {
                              "name": "stardust_upgrade_label"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9kZXBvc2l0X3JldHVybl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "storage_deposit_return_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tfdW5sb2NrX2NvbmRpdGlvbiIsImMiOjB9",
                            "node": {
                              "name": "timelock_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXRpbGl0aWVzIiwiYyI6MH0",
                            "node": {
                              "name": "utilities"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x1fd47e162b6b9f44c9db4dc4b2a9cbee33cffdac79280cd73c94dabe15cf88c4",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::Display<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
                        },
                        "json": {
                          "id": "0x1fd47e162b6b9f44c9db4dc4b2a9cbee33cffdac79280cd73c94dabe15cf88c4",
                          "fields": {
                            "contents": [
                              {
                                "key": "name",
                                "value": "{immutable_metadata.name}"
                              },
                              {
                                "key": "image_url",
                                "value": "{immutable_metadata.uri}"
                              },
                              {
                                "key": "description",
                                "value": "{immutable_metadata.description}"
                              },
                              {
                                "key": "creator",
                                "value": "{immutable_metadata.issuer_name}"
                              },
                              {
                                "key": "version",
                                "value": "{immutable_metadata.version}"
                              },
                              {
                                "key": "media_type",
                                "value": "{immutable_metadata.media_type}"
                              },
                              {
                                "key": "collection_name",
                                "value": "{immutable_metadata.collection_name}"
                              },
                              {
                                "key": "immutable_issuer",
                                "value": "{immutable_issuer}"
                              }
                            ]
                          },
                          "version": 1
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x33ef418088e3bc78c0f87fa343b18afbe9c333eb0deb901b1aeec59f4a83ea03",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0x33ef418088e3bc78c0f87fa343b18afbe9c333eb0deb901b1aeec59f4a83ea03",
                          "name": "0",
                          "value": {
                            "iota_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x378ca7e92e536f9742a755d845081920545f036e62a17a6ba06ff725c45f3125",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x378ca7e92e536f9742a755d845081920545f036e62a17a6ba06ff725c45f3125",
                          "authorizer_validator_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x4ecbc848f0a30bacf2e13085362d37a319d1f5733892cd9e8327547faf58e74d",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedIota"
                        },
                        "json": {
                          "id": "0x4ecbc848f0a30bacf2e13085362d37a319d1f5733892cd9e8327547faf58e74d",
                          "pool_id": "0x189ce5233d389956a158bb63864dcd3220907e51755c0757768dc4b9264d5a9f",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "1500000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x5042256e100219f7ef788f4211debcc4312248e2a53aa4c35e753c9176bd374e",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x5042256e100219f7ef788f4211debcc4312248e2a53aa4c35e753c9176bd374e",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x5ec356926b51943a0759e09381c9f9bb0242b899da59ceba44f00f289ce75998",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0x5ec356926b51943a0759e09381c9f9bb0242b899da59ceba44f00f289ce75998",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::iota_system_state_inner::IotaSystemStateV1>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "5",
                            "system_state_version": "1",
                            "iota_treasury_cap": {
                              "inner": {
                                "id": "0x6c70a37caebc407888246b4ae256ba13d13532e8fffedf9106b8cfd3eef5bd6b",
                                "total_supply": {
                                  "value": "31800000000000000"
                                }
                              }
                            },
                            "validators": {
                              "total_stake": "1500000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "iota_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                                    "authority_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "protocol_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      146,
                                      189,
                                      89,
                                      74,
                                      29,
                                      175,
                                      203,
                                      128,
                                      64,
                                      181,
                                      156,
                                      97,
                                      250,
                                      67,
                                      71,
                                      1,
                                      183,
                                      54,
                                      131,
                                      205,
                                      9,
                                      153,
                                      183,
                                      92,
                                      197,
                                      160,
                                      192,
                                      111,
                                      216,
                                      8,
                                      35,
                                      211,
                                      26,
                                      222,
                                      255,
                                      142,
                                      137,
                                      6,
                                      130,
                                      140,
                                      153,
                                      155,
                                      252,
                                      79,
                                      139,
                                      240,
                                      222,
                                      153
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8003/http",
                                    "next_epoch_authority_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "extra_fields": {
                                      "id": "0x4fd0224b78a2f03891d3309d972112c7ead12a1588571565ab4bde8a89862206",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x378ca7e92e536f9742a755d845081920545f036e62a17a6ba06ff725c45f3125",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x189ce5233d389956a158bb63864dcd3220907e51755c0757768dc4b9264d5a9f",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "iota_balance": "1500000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "1500000000000000",
                                    "exchange_rates": {
                                      "id": "0x0b94fafe900184ba69e5a80695318238fc61f278da209a19836db5722c7e6d8a",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_iota_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0x50baa33decdb8138885c707ae244cd56a645ec8744a9cc88bb2b2b0872d68ace",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "1500000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xbb76cf1faf706a70215818f1ca6905cd70becf97344fba01736a0b2e7fa21008",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0x4633ff272bc0cf51d68e62724122f9f5ee2d9bafb3ddf6e34eb4293d8f814d57",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0xdc244c6e5cfbf44942928bed9241b1643319ae2b69fb8c7aa9e43a547ebfc9df",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0xb00e3936d9f7502af8afa3377341621dbbf89abf6cbbf8ed02e7cee48c6a34d4",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0xea1dad74653c5ec746d558ebb72bd8eddcdaae912cfe68ecf9337e390d19d0bf",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x23504c57147f08d84e77b00373b47f927d2165d15e327af1247827d8c4a5cc0f",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "min_validator_count": "4",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "2000000000000000",
                              "validator_low_stake_threshold": "1500000000000000",
                              "validator_very_low_stake_threshold": "1000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0xaa9dac34e4ffae070cc46b5d6e887376194ef72380d7cc3f4257646cb4d86cd5",
                                "size": "0"
                              }
                            },
                            "iota_system_admin_cap": {
                              "dummy_field": false
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "safe_mode": false,
                            "safe_mode_storage_charges": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0xe4848bcc935db6a3ebe1a93610841b9b7218c6e50b315267010b1fa96b101579",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x7d2c0df15d5b44971a70027888e3182ecd31e3acaca2c0a2193d76f3656c2868",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x7d2c0df15d5b44971a70027888e3182ecd31e3acaca2c0a2193d76f3656c2868",
                          "name": "0x189ce5233d389956a158bb63864dcd3220907e51755c0757768dc4b9264d5a9f",
                          "value": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0x9eacfa7e942a18cdd47cd7fa141634e5e21c6608ff0294a49e110136f09f9e27",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x9eacfa7e942a18cdd47cd7fa141634e5e21c6608ff0294a49e110136f09f9e27",
                          "decimals": 9,
                          "name": "IOTA",
                          "symbol": "IOTA",
                          "description": "The main (gas)token of the IOTA Network.",
                          "icon_url": {
                            "url": "https://iota.org/logo.png"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xaa0c6f2564647d93f53954cff9568a8f1bf896896d3cf1038f82e8b1590dc430",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xaa0c6f2564647d93f53954cff9568a8f1bf896896d3cf1038f82e8b1590dc430",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                },
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "6izLzxwuEZCBW3s3nrYrukmHdRnSkvKkBTudEGv15Eva"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "AnQYimmAmck9f16Zd1EFQyK5qXgbvsYQRsSUL9gCf5sM"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "44KGLkjAJkTtAj2ESw2TzBKQiZ7X2Uo1YkAmL9Ty8fZw"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "5ZUN6bDYFh7oxFq1PXwWgXGNZN8M62dA7uphBDhizLo"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "9DwKupuw9jnGNXa5pyVoMWjX468DG9p5qWVJVp55ZSvL"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "Crw5YYD1dGU8oteB3zTisfkQbRcoENNT8hzyYEyzqaK2"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "C9UbsXE8ZRmHmBTaA83jg5c7sY1HMu8gRWJ1Hy3AvHL"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "9L1J7abkufuVvWb7oDSb2eYYYDFbxgNECJrfk8wnGczx"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "digest": "27H2gjTSVhF4o5uXGLE4zBNiHr38shQfcJv1jztFeTky"
                  }
                },
                {
                  "address": "0x1fd47e162b6b9f44c9db4dc4b2a9cbee33cffdac79280cd73c94dabe15cf88c4",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1fd47e162b6b9f44c9db4dc4b2a9cbee33cffdac79280cd73c94dabe15cf88c4",
                    "digest": "HqJ5Tc3UqGGux2apUHmQ7meJpU35wSbKAYuh4dmdE7S4"
                  }
                },
                {
                  "address": "0x33ef418088e3bc78c0f87fa343b18afbe9c333eb0deb901b1aeec59f4a83ea03",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x33ef418088e3bc78c0f87fa343b18afbe9c333eb0deb901b1aeec59f4a83ea03",
                    "digest": "Df27neEzwCGqFhtSw81HPyugAb6brvK5KS6T77QtgeuQ"
                  }
                },
                {
                  "address": "0x378ca7e92e536f9742a755d845081920545f036e62a17a6ba06ff725c45f3125",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x378ca7e92e536f9742a755d845081920545f036e62a17a6ba06ff725c45f3125",
                    "digest": "9B4Dc78QzKAhFFZ6sE2cPcLHqsK4yXTHM6rmDGGFb5q6"
                  }
                },
                {
                  "address": "0x4ecbc848f0a30bacf2e13085362d37a319d1f5733892cd9e8327547faf58e74d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4ecbc848f0a30bacf2e13085362d37a319d1f5733892cd9e8327547faf58e74d",
                    "digest": "35HQLTRqYUN2tRV8gsM98h3BXXTknscad4pRPKWGLCZ5"
                  }
                },
                {
                  "address": "0x5042256e100219f7ef788f4211debcc4312248e2a53aa4c35e753c9176bd374e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5042256e100219f7ef788f4211debcc4312248e2a53aa4c35e753c9176bd374e",
                    "digest": "6ZdNhqqzpavv8bt3APxScqpq4r9CV4rDri7boqNZDTN9"
                  }
                },
                {
                  "address": "0x5ec356926b51943a0759e09381c9f9bb0242b899da59ceba44f00f289ce75998",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5ec356926b51943a0759e09381c9f9bb0242b899da59ceba44f00f289ce75998",
                    "digest": "AcQB7VQf36dnL1P7gooJWyPDJ9uncvhHwisSYgydUENn"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "9aSNwrKHMrhoT57b2EeYpzDGB5Bu4gytjiCpCAyXua5J"
                  }
                },
                {
                  "address": "0x7d2c0df15d5b44971a70027888e3182ecd31e3acaca2c0a2193d76f3656c2868",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7d2c0df15d5b44971a70027888e3182ecd31e3acaca2c0a2193d76f3656c2868",
                    "digest": "fp4SPe2dsTPYhJErKrtoRhWPgEiXS78d814Mg2cXcbs"
                  }
                },
                {
                  "address": "0x9eacfa7e942a18cdd47cd7fa141634e5e21c6608ff0294a49e110136f09f9e27",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9eacfa7e942a18cdd47cd7fa141634e5e21c6608ff0294a49e110136f09f9e27",
                    "digest": "13vaqdR5n9dXSwEnJmcPw4wtXwFVaJU9nmdRcXJG51MN"
                  }
                },
                {
                  "address": "0xaa0c6f2564647d93f53954cff9568a8f1bf896896d3cf1038f82e8b1590dc430",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaa0c6f2564647d93f53954cff9568a8f1bf896896d3cf1038f82e8b1590dc430",
                    "digest": "DJNKzzxgk8UYjutepJDgCR6Nudna6GzrdDrJ4mRqw7Bf"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "3fUrRjNoRtQ1QqGCH8r4WL31rTu7vQnArVmf1c8ccB4r"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 107:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 109-184:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "3fUrRjNoRtQ1QqGCH8r4WL31rTu7vQnArVmf1c8ccB4r"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "FQsvyRc9HAiReCY3aNX4CwyAZujqeWGhZDYddNsuL8NT"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 188:
//# advance-epoch
Epoch advanced: 0

task 7, lines 190-277:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Gx5HK2D56vGgZmAwxtKV44QRvigMwhVYhxiCsCtvczxq",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransactionV2"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "3fUrRjNoRtQ1QqGCH8r4WL31rTu7vQnArVmf1c8ccB4r"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "3Bfiz4yi6GmpKUWUi3UggttQMVbuxdNSW6A9R6s7NbaK"
                  }
                },
                {
                  "address": "0x234b76cda6399e01c2aae8c506041be9445bde5424e565e77e270ab7766fd9e8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x234b76cda6399e01c2aae8c506041be9445bde5424e565e77e270ab7766fd9e8",
                    "digest": "9r3pvywHHyJpTy9axzZXjP7b97b4R6HKfmuR7bJJaH4J"
                  }
                },
                {
                  "address": "0x2d1f84cc8b187a56adc5ed50fb881fc16632781c21efa96e914abd3773305a23",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2d1f84cc8b187a56adc5ed50fb881fc16632781c21efa96e914abd3773305a23",
                    "digest": "5ECT3VXTEXZned4ed7pJ62Q9114qJTujh2QquHmNLz9K"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "6mp5pwB6mCfSUucw7B7i3BjbPNpATKWaiPeMgkWHyPyr"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "Gx5HK2D56vGgZmAwxtKV44QRvigMwhVYhxiCsCtvczxq"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
