processed 7 tasks

init:
C: object(0,0)

task 1, lines 7-32:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IGErjy/wWItmf/72ttzUzKu3TSQEH70vD+Az5UzvHvk8AAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 2, lines 34-36:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 1960800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 38:
//# run 0x3::iota_system::request_add_stake --args object(0x5) object(2,0) @validator_0 --sender C
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [88, 3, 100, 30, 5, 114, 164, 43, 143, 251, 187, 202, 169, 19, 100, 96, 215, 208, 151, 225, 50, 23, 133, 187, 2, 70, 241, 232, 235, 29, 214, 199, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 14630000,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 4, line 40:
//# create-checkpoint
Checkpoint created: 1

task 5, line 42:
//# advance-epoch
Epoch advanced: 0

task 6, lines 44-70:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IEKlC1S9ir3zTui2XEFGU8gnBYggv5MiqmufAsOnD2XyAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "15340000000000",
                "poolId": "0x5803641e0572a42b8ffbbbcaa9136460d7d097e1321785bb0246f1e8eb1dd6c7"
              }
            }
          }
        },
        {
          "cursor": "IGErjy/wWItmf/72ttzUzKu3TSQEH70vD+Az5UzvHvk8AgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000",
                "poolId": "0x5803641e0572a42b8ffbbbcaa9136460d7d097e1321785bb0246f1e8eb1dd6c7"
              }
            }
          }
        },
        {
          "cursor": "IJiyx39ZEf+O9o8CP19isDiIpNqXW5m7WzpW4pLKjqA5AgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "10000000000",
                "poolId": "0x5803641e0572a42b8ffbbbcaa9136460d7d097e1321785bb0246f1e8eb1dd6c7"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IJiyx39ZEf+O9o8CP19isDiIpNqXW5m7WzpW4pLKjqA5AgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
